#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.2.{build}
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: |
        $moduleName = 'DscLcm'
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Invoke-AppveyorInstallTask

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: |
      Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
        